#!/bin/bash

[ "$1" ] && cd "$1"
echo "##############################################################################"
pwd
echo "##############################################################################"

set -x


rounding="8,8"
transparency=0.3
full_x=240
full_y=320

darksystem=/tmp/darksystem-$(date +%s).$$.png
background=/tmp/black-$(date +%s).$$.png
logotiny=/tmp/logotiny-$(date +%s).$$.png
systemlogo=/tmp/systemlogo-$(date +%s).$$.png

if [ -f specs ]; then
	source specs
fi

primary="${primary:-#E60000}"
secondary="${secondary:-#0000FF}"

if [ "$systemtext" ]; then
	convert \
		-size 2000x2000 \
		xc:transparent \
		-font zorque \
		-fill "$primary" \
		-pointsize 200 \
		-gravity center \
		-annotate +0+0 "$systemtext" \
		-fill "$secondary" \
		-pointsize 195 \
		-gravity center \
		-annotate +0+0 "$systemtext" \
		-trim \
		+repage \
			logo-big.png
fi

# Create our rounded rectangle & watermark
convert \
	-size ${full_x}x${full_y} xc:black \
	-fill "$primary" \
	-draw "roundrectangle 2,10 236,310 $rounding" \
	-fill "$secondary" \
	-draw "roundrectangle 4,12 234,308 $rounding" \
	-fill "black" \
	-draw "roundrectangle 6,14 232,306 $rounding" \
    -font zorque \
    -fill "$primary" \
	-pointsize "7" \
    -gravity "southeast" \
    -annotate +11+14 "RetroCRT" \
    -font zorque \
    -fill "$secondary" \
	-pointsize "7" \
    -gravity "southeast" \
    -annotate +10+13 "RetroCRT" \
		$background

# shrink our large system image
convert system-big.png \
	-fuzz 1% \
	-trim \
	+repage \
	-scale 320x240 \
		system.png

# shrink our large system logo for sysetem browsing
convert logo-big.png \
	-fuzz 1% \
	-trim \
	+repage \
	-scale x50 \
		logo.png

# make a temporary logo for the upper right of our browser
convert logo-big.png \
	-fuzz 1% \
	-trim \
	+repage \
	-scale 130x30 \
		$logotiny

# create a transparent frame & center our tiny logo in it
convert \
	-size 140x40 \
	xc:transparent \
	$logotiny \
	-gravity center \
	-composite \
		$systemlogo

convert system.png \
	-resize 180x240 \
	-alpha set \
	-channel A \
	-evaluate Multiply $transparency \
	+channel \
		$darksystem

convert $background $darksystem \
	-gravity center \
	-composite $systemlogo  \
	-gravity north \
    -geometry +0+14 \
	-composite \
		background.png

rm -f $darksystem $logotiny $systemlogo $background
