#!/bin/bash

while true ; do
	while ! inotifywait -e modify "generic.xml" ; do
        for i in */theme.xml ; do
            cp -v generic.xml $i
        done
		for i in */background.png ; do
			echo "<img src=$i>"
		done > preview.html
		ssh rpib "cd raspi2png ; ./raspi2png --pngname shots/$(date +%Y%m%d_%H%M%S).png"
		sleep 3
		rsync -av --progress rpib:raspi2png/shots/ /var/www/html/fbatheme/
		rsync -av --progress --delete  --exclude .git --exclude '*swp' ./ rpib:/etc/emulationstation/themes/Beta/
		ssh rpib killall emulationstation
		date
	done
done
